CREATE database pokemon_game;

-- DROP TABLE IF EXISTS pokemon_game.pokemons;

CREATE TABLE `pokemon_game`.`pokemons` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(500) NULL,
  `available` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);

INSERT INTO pokemon_game.pokemons (id, name, description, available) VALUES
(0, '---', '---', false),
(1, 'Bulbasaur', 'Carga la semilla de una planta en su espalda desde el nacimiento, la semilla se desarrolla lentamente. Los investigadores no saben si calificarlo como una planta o animal. Es extremadamente feroz y muy difícil de capturar en el bosque.', true),
(2, 'Ivysaur', 'El Pokémon semilla, Ivysaur, forma evolucionada del Bulbasaur. El bulbo en su espalda absorbe nutrientes y se abre en una gran flor.', true),
(3, 'Venusaur', 'La forma final de la evolución de un Bulbasaur. Este Pokémon semilla absorbe los rayos del sol como una fuente de energía.', true),
(4, 'Charmander', 'Una flama arde en la punta de su cola desde su nacimiento. Se dice que el Charmander muere si su flama llega a apagarse.', true),
(5, 'Charmeleon', 'El Pokémon flamígero. Tiene garras con filo de navaja y su cola es excepcionalmente fuerte.', true),
(6, 'Charizard', 'El Pokémon de fuego. Su poderoso fuego puede derretir absolutamente todo.', true),
(7, 'Squirtle', 'Esta pequeña tortuga Pokémon jala su largo cuello hacia su caparazón para lanzar increíbles ataques de agua con sorprendente alcance y exactitud. El golpe puede ser muy poderoso.', true),
(8, 'Wartortle', 'El Pokémon tortuga. La forma evolucionada de Squirtle. Su cola larga y peluda es símbolo de su edad y sabiduría.', true),
(9, 'Blastoise', 'El Pokémon marisco, la forma evolucionada de Wartortle. La fuerza de Blastoise está más en su poder que en su velocidad. Su caparazón es como una armadura y los ataques del hidrocañón en su espalda son prácticamente imparables.', true),
(10, 'Caterpie', 'El Pokémon gusano. Caterpie usa sus ventosas de succión que tiene en sus patas para trepar árboles y alimentarse con sus hojas.', true),
(11, 'Metapod', 'La siguiente etapa del Caterpie. Ha encerrado su cuerpo en una coraza dura. Este espécimen alcanza esta etapa más rápido que cualquier otro Pokémon de esta variedad descubierto hasta ahora.', false),
(12, 'Butterfree', 'Una semana después de que Caterpie se convierte en Metapod, cambia a Butterfree. El amor de Butterfree por el néctar lo lleva a buscar flores, incluso si éstas no tienen mucho polen.', true),
(13, 'Weedle', 'El aguijón en su cabeza le garantiza a cualquier atacante que recibirá un piquete justo en donde duele.', true),
(14, 'Kakuna', 'Estado de transición entre un Weedle y un Beedrill. Los Kakuna están inactivos hasta que se convierten en Beedrill y abren.', false),
(15, 'Beedrill', 'El Pokémon abeja venenosa. Beedrill vuela rápidamente y ataca usando sus aguijones venenosos en sus patas y cola.', true),
(16, 'Pidgey', 'Es un Pokémon volador. De entre todos ellos es el más dócil y el más fácil de capturar. Un blanco perfecto para que el principiante pruebe sus habilidades Pokémon. El poder de aleteo de Pidgey crea tornados y también tormentas de arena.', true),
(17, 'Pidgeotto', 'Forma evolucionada de Pidgey. Está armado con filosas garras y se lanza desde el cielo para atrapar a su presa. Al contrario del dócil Pidgey, el Pidgeotto puede ser peligroso. Aproxímate con extremo cuidado.', true),
(18, 'Pidgeot', 'El Pokémon ave. La forma evolucionada de Pidgeotto. Puede volar al doble de la velocidad del sonido y a una altura de casi 1 kilómetro.', true),
(19, 'Rattata', 'Pokémon del bosque. Le gusta el queso, las nueces, la fruta y las moras. También sale a campo abierto para robar comida de viajeros tontos.', true),
(20, 'Raticate', 'El Pokémon ratón y forma evolucionada de Rattata. Raticate puede roer todo, pues sus dientes nunca dejan de crecer.', true),
(21, 'Spearow', 'Al contrario del Pidgey, el Spearow tiene un mal carácter. Es muy salvaje y a veces ataca a otros Pokémon y a los humanos.', true),
(22, 'Fearow', 'El Pokémon pico. La forma evolucionada de Spearow. Sus largas y poderosas alas le permiten volar durante todo un día. La fuerza demoledora de su pico es tremenda.', true),
(23, 'Ekans', 'Es fácil encontrarlo en praderas y zonas similares. A este Pokémon le basta con sacar la lengua para detectar el peligro.', true),
(24, 'Arbok', 'Este Pokémon es tremendamente fuerte, puede oprimir cualquier cosa con su cuerpo y hasta es capaz de estrujar un barril de acero. Una vez que Arbok se enrosca a su víctima, no hay forma de escapar de su asfixiante abrazo.', true),
(25, 'Pikachu', 'El Pokémon ratón. Puede generar ataques eléctricos en las bolitas que tiene en ambas mejillas.', true),
(26, 'Raichu', 'Un ratón Pokémon del elemento eléctrico. Raichu es la forma evolucionada de Pikachu. Puede hacer descargas de más de 100 mil voltios suficientes para dejar inconsciente a un Dragonite.', true),
(27, 'Sandshrew', 'El Pokémon ratón. Sandshrew odia la humedad y vive en hoyos secos. Se protege al hacerse bolita.', true),
(28, 'Sandslash', 'El Pokémon ratón. La forma evolucionada de Sandshrew. Ataca a sus oponentes con las espinas de su espalda.', true),
(29, 'Nidoran ♀', 'Nidoran hembra, tipo veneno. Es muy poderosa con sus ataques, pero sus espinas son más pequeñas que las del macho.', true),
(30, 'Nidorina', 'El Pokémon tipo veneno. La forma evolucionada del Nidoran hembra. Emite ondas supersónicas con su boca para confundir a sus enemigos.', true),
(31, 'Nidoqueen', 'La Pokémon taladro. Nidoqueen tiene una piel muy gruesa que protege todo su cuerpo y la protege de cualquier técnica con que se le ataque.', true),
(32, 'Nidoran ♂', 'Nidoran macho, el Pokémon tipo veneno. Su cuerno es más grande que el de la hembra y su ataque de cuerno es muy poderoso.', true),
(33, 'Nidorino', 'El Pokémon tipo veneno. La forma evolucionada del Nidoran macho. Su cuerno, altamente evolucionado, es extremadamente poderoso.', true),
(34, 'Nidoking', 'El Pokémon taladro, Nidoking balancea su larga cola para crear distancia luego la recarga con toda la fuerza de su cuerpo.', true),
(35, 'Clefairy', 'Este pícaro Pokémon es amistoso y pacífico. Se cree que vive dentro del Monte Lunar, aunque muy pocos han sido vistos por humanos.', true),
(36, 'Clefable', 'Una forma avanzada de Clefairy. Estas criaturas únicas están entre los Pokémon más raros del mundo.', true),
(37, 'Vulpix', 'Un Pokémon zorro. Sus seis colas son extremadamente hermosas. Al evolucionar produce aún más colas. Vulpix usa poderosos ataques con llamas.', true),
(38, 'Ninetales', 'El Pokémon zorro. La forma evolucionada de Vulpix. Tiene nueve colas y una brillante piel dorada. Se dice que los Ninetales llegan a tener largas vidas.', true),
(39, 'Jigglypuff', 'Un Pokémon globo. Tiene ojos grandes y amigables y canta una canción muy placentera.', true),
(40, 'Wigglytuff', 'Wigglytuff tiene unos ojos enormes con forma de platillo, que siempre están cubiertos de lágrimas. Si se le metiera algo en el ojo, enseguida se le saldría solo.', true),
(41, 'Zubat', 'Pokémon volador con poderes supersónicos. Vive en cuevas y odia salir a volar con luz del día.', true),
(42, 'Golbat', 'Pokémon murciélago. La forma evolucionada de Zubat. Tiene cuatro colmillos filosos y emite ondas supersónicas más poderosas que las de Zubat.', true),
(43, 'Oddish', 'Es típico encontrarlo vagando por los bosques y va regando polen mientras camina.', true),
(44, 'Gloom', 'El Pokémon alga. Gloom emite un olor muy desagradable. Es muy fuerte contra los Pokémon tipo agua pero muy débil contra los de tipo fuego y voladores.', true),
(45, 'Vileplume', 'El Pokémon flor. Usando los pétalos de flor más grandes del mundo, este lanza grandes cantidades de polen que causan reacciones alérgicas.', true),
(46, 'Paras', 'El Pokémon hongo. En su lomo crecen extraños hongos. Paras tiene las cualidades de los Pokémon bicho y hierba.', true),
(47, 'Parasect', 'El Pokémon hongo. Pelea usando esporas veneno, que provienen de la capa de hongo en su espalda.', true),
(48, 'Venonat', 'Un Pokémon insecto. Sus ojos funcionan como radar permitiéndole ver en la oscuridad.', true),
(49, 'Venomoth', 'Una forma evolucionada del Venonat. Pequeñas escamas en sus alas se dispersan cuando este aletea.', true),
(50, 'Diglett', 'El movimiento de esos Pokémon subterráneos puede ser fácilmente detectado por sus huellas en la tierra revuelta.', true),
(51, 'Dugtrio', 'Se forma cuando tres Diglett se combinan. Este Pokémon hace túneles profundos bajo la superficie de la tierra.', true),
(52, 'Meowth', 'El Pokémon gato rasguño. Meowth adora maullar en la noche para conseguir monedas y otros objetos que brillen, pero pasa la mayor parte del día durmiendo.', true),
(53, 'Persian', 'El Pokémon gato elegante y la forma evolucionada de Meowth. Persian camina silencioso gracias a sus ágiles músculos. Se abalanza sobre su presa a la velocidad de la luz.', true),
(54, 'Psyduck', 'Pokémon acuático. Cuando la jaqueca de Psyduck se vuelve severa, genera poderes asombrosos.', true),
(55, 'Golduck', 'El Pokémon pato. La forma evolucionada de Psyduck. Golduck es muy ágil en usar sus manos y pies palmeadas para hacerlo el Pokémon nadador más rápido de todos.', true),
(56, 'Mankey', 'Un Pokémon simio del tipo pelea conocido por sus miembros superiores que dan poderosos golpes. Aunque el Mankey generalmente es calmado, tiene un mal temperamento. Cuando el Mankey empieza a arremeter, es imposible detenerlo.', true),
(57, 'Primeape', 'Si haces contacto visual con esta forma evolucionada de Mankey, se terminó todo. El Primeape te perseguirá para siempre. Cuando el Primeape inicia su ataque más fuerte, arremeter, queda completamente fuera de control.', true),
(58, 'Growlithe', 'Un cachorro Pokémon de buen carácter y gran inteligencia. Aleja a sus enemigos con ladridos y mordidas.', true),
(59, 'Arcanine', 'Un Pokémon legendario. La forma evolucionada de Growlithe. Arcanine es conocido por su bravura y gran lealtad. Growlithe evoluciona en Arcanine con el uso de una roca fuego.', true),
(60, 'Poliwag', 'El Pokémon renacuajo. No tiene brazos, pero su cola lo hace un nadador fuerte.', true),
(61, 'Poliwhirl', 'El Pokémon renacuajo. Sus músculos altamente desarrollados le permiten moverse eficazmente en tierra, pero es mucho más ágil en el agua.', true),
(62, 'Poliwrath', 'El Pokémon renacuajo. Poliwrath es un excelente nadador y sus poderosos músculos hacen sus ataques puedan llegar a ser extremadamente efectivos.', true),
(63, 'Abra', 'Un Pokémon con poderes psíquicos. Duerme 18 horas al día, pero emplea la telequinesis aún mientras duerme.', true),
(64, 'Kadabra', 'Un Pokémon psíquico. La forma evolucionada de Abra. Emplea poderosos ataques telequinéticos.', true),
(65, 'Alakazam', 'Un Pokémon psíquico. Este Pokémon usa ataques psíquicos para superar a sus oponentes.', true),
(66, 'Machop', 'Su cuerpo está hecho de puro músculo. Su ataque especial es el lanzamiento letal.', true),
(67, 'Machoke', 'El Pokémon superpoderoso. Tiene tanta fuerza como para levantar un camión con una mano. Con frecuencia lo usan para trabajos muy pesados.', true),
(68, 'Machamp', 'El Pokémon superpoder. Tipo peleador. Los cuatro brazos de Machamp se mueven por reflejo, lo que lo hace muy veloz y le permite lanzar golpes muy rápido.', true),
(69, 'Bellsprout', 'El Pokémon flor. Tipo planta y veneno. Bellsprout ama las altas temperaturas y la humedad. Puede alcanzar una gran velocidad cuando extiende sus raíces para tomar algo.', true),
(70, 'Weepinbell', 'El Pokémon matamoscas. Weepinbell parece una planta y cubre a sus oponentes con un polvo venenoso para atraparlos.', true),
(71, 'Victreebel', 'Tiene una enredadera que le sale de la cabeza. Cuando la agita y colea, recuerda a un animal y así consigue atraer a sus presas. Si se le acerca un rival, lo engulle.', true),
(72, 'Tentacool', 'Un Pokémon medusa. El 99% de su cuerpo está hecho de agua.', true),
(73, 'Tentacruel', 'Un Pokémon medusa. Una forma evolucionada del Tentacool. Sus numerosos tentáculos le sirven como un arma poderosa. Es conocido como el gangster del mar.', true),
(74, 'Geodude', 'El Pokémon roca. Geodude tiene un increíble poder defensivo que lo hace distualmente resistente a cualquier ataque físico.', true),
(75, 'Graveler', 'Graveler crece alimentándose a base de piedras. Y, según parece, las prefiere cubiertas de musgo. Cada día se abre camino comiéndose toneladas de rocas.', true),
(76, 'Golem', 'Un Pokémon megatón. Una vez al año cambia su concha de roca y se hace más grande.', true),
(77, 'Ponyta', 'Un caballo de fuego. La crin de este hermoso Pokémon está hecha de intensas llamas.', true),
(78, 'Rapidash', 'El Pokémon caballo fuego. De tipo fuego. Rapidash ama galopar. Siempre quiere competir cuando ve un objeto moverse muy rápido.', true),
(79, 'Slowpoke', 'El Pokémon bobo. Nadie puede decir lo que Slowpoke está pensando, si es que piensa. Su especialidad es pescar con la cola.', true),
(80, 'Slowbro', 'El Pokémon granjero ermitaño. Slowbro es capaz de utilizar poderosos ataques psíquicos, pero prefiere evitar los conflictos.', true),
(81, 'Magnemite', 'El Pokémon magneto. Es capaz de flotar en el aire y emite ondas trueno a través de las unidades en forma de magneto ubicadas a sus lados.', true),
(82, 'Magneton', 'El Pokémon magneto. La forma evolucionada de Magnemite. Sus poderes antigravitacionales le permiten flotar y pueden emitir poderosos campos eléctricos y magnéticos.', true),
(83, 'Farfetch''d', 'Farfetch''d, el pato salvaje Pokémon. Este Pokémon extremadamente raro siempre se encuentra sujetando un puerro o un cebollín verde que usa para construir su nido.', true),
(84, 'Doduo', 'El Pokémon ave gemela. Cuando sus cabezas se empiezan a pelear entre ellas, Doduo ha quedado incapacitado.', true),
(85, 'Dodrio', 'Un ave Pokémon de tres cabezas que puede correr más rápido de lo que vuela. Sus tres cabezas representan a la dicha, la pena y la ira.', true),
(86, 'Seel', 'Seel busca a sus presas en aguas heladas, bajo las capas de hielo. Cuando necesita respirar, abre un agujero en el hielo con la afilada protuberancia que tiene encima de la cabeza.', true),
(87, 'Dewgong', 'La forma evolucionada de Seel. Este Pokémon de agua y hielo puede resistir muy bajas temperaturas.', true),
(88, 'Grimer', 'Un Pokémon de lodo. Nacido del lodo, esos Pokémon se especializan en ataques de lodo.', true),
(89, 'Muk', 'Forma evolucionada del Grimer. Tengan mucha precaución, ya que su forma viscosa contiene veneno.', true),
(90, 'Shellder', 'Su caparazón repele cualquier tipo de ataque. Sólo cuando abre su caparazón es vulnerable.', true),
(91, 'Cloyster', 'El Pokémon marino. Su concha es increíblemente fuerte y resiste hasta una bomba. Solo abre su concha cuando ataca.', true),
(92, 'Gastly', 'Un Pokémon fantasma. Es normalmente invisible. Su especialidad es la hipnosis', true),
(93, 'Haunter', 'El Pokémon gas. Después de evolucionar de Gastly, este Haunter puede aprender a comer sueños y ataques psíquicos.', true),
(94, 'Gengar', 'Un Pokémon sombra. La forma evolucionada de Haunter. Los detalles sobre este Pokémon son desconocidos.', true),
(95, 'Onix', 'Onix, el Pokémon serpiente roca. Al girar su cuerpo grande y poderoso, Onix puede perforar rápidamente la tierra a 80 km/h.', true),
(96, 'Drowzee', 'El Pokémon hipnótico. Se dice que se alimenta de los sueños de sus oponentes y es conocido por su poderoso ataque psíquico.', true),
(97, 'Hypno', 'Un Pokémon hipnótico. Tiene un aparato como péndulo y realiza ataques hipnóticos.', true),
(98, 'Krabby', 'El Pokémon cangrejo. Vive en playas arenosas en las madrigueras que excava. Las pinzas de Krabby pueden volver a crecer si se rompen en la batalla.', true),
(99, 'Kingler', 'La forma evolucionada de Krabby. Un Pokémon tenaz cuyas pinzas endurecidas pueden cerrar con el poder de 10.000 caballos de fuerza.', true),
(100, 'Voltorb', 'Este misterioso Pokémon usa fuertes ataques eléctricos y a menudo se encuentra cerca de plantas de energía. Use extrema precaución porque puede explotar sin advertencias.', true),
(101, 'Electrode', 'La forma evolucionada de Voltorb. La energía altamente concentrada causa que este Pokémon explote imprevisiblemente. También es conocido como la "Bola Bomba".', true),
(102, 'Exeggcute', 'Un huevo Pokémon. Aunque se parece a un huevo, se sabe que es un pariente más cercano de las semillas de una planta.', true),
(103, 'Exeggutor', 'Un Pokémon palmera. También conocido como la selva tropical andante. Cada palmera tiene una cara distinta y su propio carácter. Su ataque especial es la hipnosis.', true),
(104, 'Cubone', 'Cubone, el Pokémon solitario. Tipo tierra. Cubone usa un cráneo como casco para ocultar su cara mientras vierte lágrimas por la madre que perdió hace mucho. Llora con intensidad para expresar su soledad, además siempre lleva un hueso largo y grueso.', true),
(105, 'Marowak', 'Un Pokémon porta huesos. A pesar de su pequeño tamaño, su fuerza defensiva y ofensiva son impresionantes.', true),
(106, 'Hitmonlee', 'El Pokémon pateador. Puede extender y retraer sus piernas a voluntad para patear a sus oponentes a cualquier distancia.', true),
(107, 'Hitmonchan', 'Un hábil Pokémon peleador que tiene un golpe increíblemente rápido.', true),
(108, 'Lickitung', 'El Pokémon lamedor. Usa su lengua que es 2 veces más larga que su cuerpo para pelear y para obtener comida.', true),
(109, 'Koffing', 'El Pokémon gas veneno. Koffing rocía el aire gracias a los gases tóxicos que contiene, tiene un olor fétido y pueden explotar.', true),
(110, 'Weezing', 'A Weezing le encantan los gases que emanan de los desperdicios que quedan en la cocina. Este Pokémon busca casas sucias y abandonadas para crear su hogar. De noche, cuando los habitantes de la casa duermen, va a por la basura.', true),
(111, 'Rhyhorn', 'El Pokémon clavos. Rhyhorn embiste temerariamente de frente, arrasando con todo lo que se interponga en su camino.', true),
(112, 'Rhydon', 'La forma evolucionada de Rhyhorn es conocida como el Pokémon taladro. Su largo cuerno le da un formidable poder de ataque.', true),
(113, 'Chansey', 'El Pokémon huevo y la forma evolucionada de Happiny. Chansey es un Pokémon amable que da huevos a los que están enfermos o heridos.', true),
(114, 'Tangela', 'Un Pokémon enredadera. Su cuerpo está envuelto en ramas. El resto de su forma está oculto bajo esas ramas.', true),
(115, 'Kangaskhan', 'Un Pokémon padre. Aunque alguna vez estuvieron cerca de extinguirse, ahora están protegidos por la ley y habitan en la Zona Safari. Aproxímese con extrema precaución, el Kangaskhan es un Pokémon raro que cría a su hijo en una bolsa, atacarán ferozmente y sin advertencia si sienten que su cría está amenazada de algún modo.', true),
(116, 'Horsea', 'Un Pokémon dragón. Esta especie única de Pokémon pone miles de huevos cada primavera y luego el macho se encarga de criarlos.', true),
(117, 'Seadra', 'Un Pokémon dragón. La forma evolucionada de Horsea. Seadra tiene un temperamento violento y las espinas que cubren su cuerpo dejan inconsciente a su víctima.', true),
(118, 'Goldeen', 'El Pokémon pez color. Tipo agua. Cuando la temperatura sube, Goldeen forma grupos y nada río arriba. Dicen que esa es la señal de que la primavera ha llegado.', true),
(119, 'Seaking', 'El Pokémon pez dorado. Seaking es la forma evolucionada de Goldeen. Su cuerno en forma de barrena es capaz de romper cualquier piedra.', true),
(120, 'Staryu', 'El centro de este Pokémon acuático brilla en un arco iris de siete colores, un centro que es valuado por algunos como una joya.', true),
(121, 'Starmie', 'La parte central de Starmie (el núcleo brillante) resplandece con siete colores distintos. Debido a su naturaleza luminosa, a este Pokémon se le ha dado el apelativo de "la gema del mar".', true),
(122, 'Mr. Mime', 'El Pokémon barrera. Usa su pantomima para aparecer paredes reales. Debido a que fue recientemente descubierto, la información sobre este Pokémon es extremadamente limitada.', true),
(123, 'Scyther', 'El Pokémon mantis. Sus garras son filosas como espadas y es un volador poderoso. Este Pokémon rara vez es visto por humanos y casi nunca capturado.', true),
(124, 'Jynx', 'El Pokémon de forma humana. Este Pokémon tiene algunos poderes inusuales. Su ataque especial es el beso amoroso, que deja a su oponente en un profundo sueño.', true),
(125, 'Electabuzz', 'El Pokémon eléctrico. Electabuzz es la forma evolucionada de Elekid. Debido a la poderosa corriente eléctrica que corre constantemente por su cuerpo, Electabuzz parece que brilla.', true),
(126, 'Magmar', 'El Pokémon escupe fuego. Su cuerpo se mantiene a altas temperaturas. Solo ha sido descubierto en volcanes activos.', true),
(127, 'Pinsir', 'Este temido y peligroso Pokémon usa sus poderosas pinzas para prensar y aplastar a sus oponentes.', true),
(128, 'Tauros', 'Un Pokémon toro salvaje. Cuando se golpea a sí mismo con sus tres colas, su ataque es una poderosa fuerza destructiva. \n Su movimiento característico es placaje. Dado a su carácter dócil, no te atacaran sin haber sido molestados primero.', true),
(129, 'Magikarp', 'El Pokémon pez. Magikarp puede vivir en el agua más sucia. Salta muy alto y evoluciona en Gyarados.', true),
(130, 'Gyarados', 'Este Pokémon tiene un temperamento malvado así que ten mucha precaución. Sus colmillos pueden destrozar rocas y sus escamas son más duras que el acero.', true),
(131, 'Lapras', 'Este Pokémon intelectualmente avanzado es capaz de entender el idioma humano. Por su suave temperamento, Lapras prefiere cargar a los humanos en su espalda a entablar batallas Pokémon.', true),
(132, 'Ditto', 'Un Pokémon transformer. Es capaz de reordenar las células de su cuerpo y asumir cualquier forma. Su único ataque es la transformación.', true),
(133, 'Eevee', 'El Pokémon evolutivo.  Eevee evoluciona en uno de estos tres Pokémon dependiendo de qué roca se use con él. Usando una roca de fuego producirás un Flareon, el Pokémon de fuego. Una roca acuática producirá un Vaporeon, el Pokémon burbuja hielo. Y una roca trueno produce un Jolteon, el Pokémon rayo.', true),
(134, 'Vaporeon', 'Vaporeon, el Pokémon que hace burbujas. A Vaporeon le encanta el agua limpia y fresca y también puede deshacer su cuerpo dentro del agua.', true),
(135, 'Jolteon', 'El Pokémon rayo. Cuando se enoja o se asusta el pelo de su cuerpo se convierte en agujas que disparan a sus oponentes. Absorbe los átomos cargados y pueden producir 10.000 voltios de electricidad.', true),
(136, 'Flareon', 'El Pokémon flama. Flareon es la forma evolucionada de Eevee, el aire que emana es encendido por una flama dentro de su cuerpo y la expulsa como fuego.', true),
(137, 'Porygon', 'Porygon es capaz de convertirse otra vez en datos informáticos y de entrar en el ciberespacio. Tiene protección anti-copia, así que es imposible duplicarlo.', true),
(138, 'Omanyte', 'El Pokémon espiral. Vivía hace dos millones de años. Investigaciones indican que podían controlar su sistema de flotación introduciendo y midiendo aire con sus conchas.', true),
(139, 'Omastar', 'La forma evolucionada de Omanyte. Este Pokémon extinto usaba agudos colmillos para romper las conchas de sus presas para alimentarse.', true),
(140, 'Kabuto', 'Kabuto, el Pokémon antiguo. Aunque se piensa que este Pokémon ahora está extinto, este tenía un duro caparazón que protegía a su cuerpo y se piensa que era un poderoso nadador.', true),
(141, 'Kabutops', 'Se cree que esos Pokémon se extinguieron hace decenas de miles de años, los detalles de su comportamiento están envueltos en el misterio. Aunque algunos han especulado que aún pueden existir, ninguno de estos Pokémon han sido vistos jamas.', true),
(142, 'Aerodactyl', 'Un Pokémon volador extinto. Sus largos colmillos sugieren que era un carnívoro. Sus filosas garras eran tal vez usadas para capturar a sus presas.', true),
(143, 'Snorlax', 'El Pokémon dormilón. Solo despierta para comer. Snorlax es la especie más pesada de los Pokémon conocidos. Algunos pesan más de 500 kilogramos. El hambre de Snorlax no está satisfecho hasta que ingiere 400 kilogramos de comida. Entonces se vuelve a dormir.', true),
(144, 'Articuno', 'El Pokémon helado. Este legendario Pokémon con alas como delgadas hojas de hielo, se cree que posee la habilidad de congelar el vapor de agua y crear nieve.', true),
(145, 'Zapdos', 'El Pokémon eléctrico legendario. Zapdos tiene unos segmentos eléctricos de vuelo y el movimiento de sus alas puede crear rayos.', true),
(146, 'Moltres', 'Un Pokémon legendario. Sus virtudes simbolizan las competencias de la liga Pokémon. Cuando está herido, Moltres entra en la lava de un volcán para que las temperaturas extremas le ayuden a curar sus heridas. Dicen que cuando Moltres aparece, es porque la primavera está por llegar.', true),
(147, 'Dratini', 'El Pokémon dragón. Dratini cambia de piel conforme crece, a menudo lo hace mientras se esconde tras una cascada grande y poderosa.', true),
(148, 'Dragonair', 'El Pokémon dragón. Un Pokémon legendario que puede hacer llover o nevar libremente. Se dice que es capaz de volar a pesar de no tener alas.', true),
(149, 'Dragonite', 'El Pokémon dragón. Este Pokémon extremadamente raro y altamente inteligente, es capaz de volar más rápido que cualquier otro Pokémon.', true),
(150, 'Mewtwo', 'Pokémon desconocido, no hay datos disponibles.', true),
(151, 'Mew', 'Dicen que Mew posee el mapa genético de todos los Pokémon. Puede hacerse invisible cuando quiere, así que pasa desapercibido cada vez que se le acerca alguien.', true);

Select * from pokemon_game.pokemons;