-- DROP TABLE IF EXISTS pokemon_game.attacks;

CREATE TABLE `pokemon_game`.`attacks` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
	`damage` INT NULL,
	`defense` INT NULL,
  `description` VARCHAR(500) NULL,
	type_id INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
FOREIGN KEY (type_id) REFERENCES pokemon_game.types(id));

INSERT INTO pokemon_game.attacks (id, name, damage, defense, type_id, description) VALUES
(1, "Burbuja", 20, 0, 1, "Lanza burbujas en tres direcciones y causa daño a los enemigos a su alcance. También puede reducir su velocidad de desplazamiento."),
(2,"Cascada",80,0,1,"El usuario se acerca a los enemigos frente a sí y levanta columnas de agua con las que les inflige daño."),
(3,"Hidrobomba",110,0,1,"Expulsa agua a mucha presión y daña a los rivales, además de empujarlos."),
(4,"Martillazo",100,0,1,"Martillazo causa daño y tiene una alta probabilidad de dar un golpe crítico."),
(5,"Pistola de agua",40,0,1,"Lanza un chorro de agua que inflige daño a los Pokémon rivales a los que golpea. Este movimiento tiene una probabilidad fija de ser crítico."),
(6,"Rayo Burbuja",65,0,1,"Erige un escudo a su alrededor y lanza un chorro de burbujas en la dirección seleccionada que inflige daño a los rivales. Tras recorrer cierta distancia, las burbujas siguen flotando temporalmente y si algún Pokémon rival toca una, la burbuja lo envuelve y lo incapacita temporalmente."),
(7,"Refugio",0,40,1,"El usuario se resguarda en su dura coraza y reduce por un tiempo el daño que recibe."),
(8,"Surf",90,0,1,"Genera una gran ola con la que carga hacia delante. Daña a los enemigos a los que alcanza."),
(9,"Tenaza",35,0,1,"El pokemon atrapa al pokemon rival."),
(10,"Chupavidas",80,0,2,"Absorbe la sangre de los enemigos que tiene delante y recupera PS equivalentes a una parte del daño causado."),
(11,"Disparo demora",80,0,2,"Lanza hacia delante un hilo viscoso que suele reducir la velocidad de desplazamiento de los enemigos alcanzados."),
(12,"Doble ataque",25,0,2,"Doble ataque causa daño golpeando dos veces en cada uso."),
(13,"Pin misil",25,0,2,"Pin misil causa daño, golpeando al objetivo de 2 a 5 veces en un mismo turno. El movimiento tiene una probabilidad del 37,5% de golpear 2 veces, un 37,5% de hacerlo 3 veces, un 12,5% de 4 veces, y un 12,5% de 5 veces."),
(14,"Furia Dragon",40,0,3,"Lanza un potente ataque de fuego."),
(15,"Impactrueno",40,0,4,"Acumula electricidad y luego la libera contra los enemigos frente a sí, causándoles daño. Puede paralizar."),
(16,"Onda trueno",20,20,4,"Lanza un proyectil al rival seleccionado, lo que inflige daño y lo paraliza."),
(17,"Puño trueno",75,0,4,"Golpea al rival con el puño cargado de electricidad."),
(18,"Rayo",90,0,4,"Emite una poderosa descarga eléctrica que inflige daño e incapacita a los rivales en el área de efecto."),
(19,"Trueno",110,0,4,"Ataca con unos poderosos rayos que infligen daño a los rivales en el área de efecto."),
(20,"Lengüetazo",30,30,5,"Lame a los enemigos que tiene a su alrededor con una larga lengua causándoles daño y lo paraliza."),
(21,"Rayo confuso",50,0,5,"El usuario emite una luz siniestra que a menudo confunde a los enemigos a su alrededor."),
(22,"Tinieblas",40,0,5,"Lanza rayos de oscuridad que infligen daño al oponente."),
(23,"Ascuas",40,0,6,"Lanza una llamarada que se separa en tres direcciones al chocar contra el suelo y daña a los enemigos a su alcance. Puede causar quemaduras."),
(24,"Giro de fuego",35,0,6,"Crea una espiral de fuego a su alrededor que daña a los enemigos alcanzados. Puede causar quemaduras."),
(25,"Lanzallamas",90,0,6,"Ataca con una gran ráfaga de fuego que daña poco a poco a los objetivos alcanzados. Puede causar quemaduras."),
(26,"Llamarada",110,0,6,"Lanza una enorme llamarada que incinera el suelo e inflige daño continuo a los rivales."),
(27,"Puño de fuego",75,0,6,"Ataca a los enemigos frente a sí con un fuerte puñetazo ardiente. Puede causar quemaduras."),
(28,"Neblina",0,0,7,"Neblina evita que el pokemón sea atacado."),
(29,"Niebla",30,30,7,"Niebla evita que el pokemón sea atacado e inflige daño"),
(30,"Puño hielo",75,75,7,"Ataca a los enemigos frente a sí con un fuerte puñetazo congelado. Puede llegar a congelar al oponente."),
(31,"Rayo aurora",65,0,7,"Lanza un potente rayo que daña al enemigo."),
(32,"Rayo hielo",90,0,7,"Lanza un potente rayo que daña al enemigo."),
(33,"Ventisca",110,0,7,"Genera a su alrededor una tormenta helada que daña a los enemigos adyacentes. Puede congelar."),
(34,"Contraataque",30,15,8,"Después de recibir daño, ataca y se recupera (en parte) del daño recibido."),
(35,"Doble patada",60,0,8,"Golpea al rival, causando el doble de daño."),
(36,"Golpe Karate",50,0,8,"Propina un manotazo cortante a los rivales."),
(37,"Patada baja",45,0,8,"Da una patada baja al oponente."),
(38,"Patada giro",60,0,8,"Da una serie de patadas mientras gira."),
(39,"Patada salto",100,0,8,"Salta hacia delante para propinar una gran patada."),
(40,"Patada salto alta",130,0,8,"Salta hacia delante para propinar una gran patada que inflige aún más daño que Patada salto."),
(41,"Sísmico",70,0,8,"Produce un movimiento debajo del oponente infligiendo daño."),
(42,"Sumisión",80,0,8,"Se vuelve imparable y aumenta su velocidad de desplazamiento. El siguiente ataque básico inflige daño adicional e inmoviliza al rival después de estamparlo contra el suelo, tras lo que el índice de golpe crítico y la velocidad de ataque aumentan temporalmente."),
(43,"Afilar",0,20,9,"Devuelve puntos de vida al usuario."),
(44,"Agarre",55,0,9,"Agarre causa daño y no tiene ningún efecto secundario."),
(45,"Anulación",0,0,9,"Anulación permite hacer que el oponente pierda un turno."),
(46,"Arañazo",40,0,9,"Realiza un ataque utilizando sus garras."),
(47,"Atadura",15,15,9,"Atadura causa daño y no permite realizar un movimiento en el siguiente turno."),
(48,"Ataque furia",30,0,9,"Ataque furia permite infligir el doble de daño."),
(49,"Ataque rápido",40,0,9,"Embiste a una velocidad de vértigo e inflige daño a los rivales con los que entra en contacto."),
(50,"Atizar",80,0,9,"Golpe directo muy potente."),
(51,"Autodestrucción",200,0,9,"El usuario se acerca a los enemigos a su alrededor y provoca una gran explosión para infligirles daño. Pierde todos sus PS."),
(52,"Beso amoroso",0,0,9,"Beso amoroso duerme al objetivo."),
(53,"Bomba huevo",100,0,9,"Lanza un huevo a la ubicación seleccionada que, tras explotar, inflige daño a los rivales en el área de efecto y los lanza por los aires."),
(54,"Bomba sónica",30,0,9,"Lanza una potente bomba de sonido."),
(55,"Bombardeo",45,0,9,"Lanza varios ataques a la vez."),
(56,"Cabezazo",130,130,9,"Propina un poderoso cabezazo a los rivales y los incapacita."),
(57,"Canto",0,0,9,"Canto es un movimiento de sonido que duerme al objetivo."),
(58,"Chirrido",10,0,9,"Chirrido es un ataque de sonido."),
(59,"Clavo cañón",40,0,9,"Realiza un ataque lanzando clavos (espinas) al oponente."),
(60,"Constricción",30,30,9,"Atrapa al oponente e inflige daño."),
(61,"Conversión",0,0,9,"Conversión cambia el tipo del usuario al tipo del oponente."),
(62,"Cornada",65,0,9,"Ataca al oponente a través de sus poderosos cuernos o espinas."),
(63,"Corte",50,0,9,"Daña al oponente a través de un ataque rápido."),
(64,"Cuchillada",70,0,9,"Daña al oponente a través de un ataque rápido."),
(65,"Danza espada",50,0,9,"Daña al oponente a través de un ataque rápido."),
(66,"Derribo",90,0,9,"Carga hacia delante con gran ímpetu dañando a todos los enemigos a los que alcanza."),
(67,"Desarrollo",0,20,9,"Desarrollo aumenta la cantidad de puntos de vida que tenga el usuario."),
(68,"Deslumbrar",0,0,9,"Deslumbrar provoca parálisis al oponente."),
(69,"Destello",0,0,9,"Deslumbra a los enemigos a su alrededor con una luz cegadora que a menudo reduce su velocidad de desplazamiento."),
(70,"Destructor",50,0,9,"Destructor causa daño y no tiene ningún efecto secundario."),
(71,"Día de pago",40,0,9,"Causa daño lanzando monedas y no tiene ningún efecto secundario."),
(72,"Doble bofetón",45,0,9,"Doble bofetón causa daño, golpeando al objetivo de 2 a 5 veces en un mismo turno."),
(73,"Doble equipo",0,30,9,"Doble equipo aumenta el nivel de vida del usuario."),
(74,"Doble filo",120,0,9,"Doble filo es un ataque doble y poderoso."),
(75,"Explosión",250,-50,9,"Explosión genera un daño crítico en el oponente. El usuario también recibe daño."),
(76,"Foco energía",0,30,9,"El usuario respira hondo y concentra energía para aumentar sus puntos de vida."),
(77,"Fortaleza",0,20,9,"Concentra energía en su cuerpo para endurecerlo y aumentar puntos de vida."),
(78,"Fuerza",80,0,9,"Realiza un potente ataque al oponente."),
(79,"Furia",20,10,9,"Realiza un potente ataque al oponente."),
(80,"Golpe cabeza",70,0,9,"Embiste al oponente infligiendo un daño considerable."),
(81,"Golpe cuerpo",85,0,9,"Realiza un ataque al oponente utilizando todo el cuerpo."),
(82,"Golpes furia",40,40,9,"Ataca al rival y lo deja incapacitado."),
(83,"Guillotina",1000,0,9,"Guillotina provoca un golpe fulminante."),
(84,"Hipercolmillo",80,0,9,"Hipercolmillo genera daño al oponente. No tiene efectos secundarios."),
(85,"Hiperrayo",150,0,9,"Concentra energía y la lanza en un potente ataque que inflige un daño tremendo a los enemigos alcanzados."),
(86,"Látigo",40,0,9,"Mueve la cola frente al rival y luego lanza un ataque, lo que le inflige daño."),
(87, "Malicioso", 0, 0, 9, "Lanza una mirada intimidatoria a los enemigos cercanos. Con lo cual los paraliza."),
(88, "Megapatada", 120, 0, 9, "Potente patada que inflige mucho daño al oponente."),
(89, "Megapuño", 80, 0, 9, "El pokemon concentra una gran cantidad de energía al puño antes de golpear al oponente. Lo cuál hace que el golpe inflija mucho daño."),
(90, "Meteoros",60,0,9, "Lanza rayos en forma de estrella que infligen daño a los Pokémon rivales."),
(91, "Metrónomo", 40, 40, 9, "El pokemón realiza un movimiento con las manos similar al movimiento de un metrónomo, esto confunde al oponente y luego el pokemón ataca. El rival pierde un turno."),
(92, "Mimético", 60, 0, 9, "Mimético permite al usuario elegir uno de los movimientos del objetivo y copiarlo. Este movimiento reemplaza a mimético hasta que el usuario sea cambiado por otro Pokémon, se debilite o el combate termine."),
(93, "Ovocuración", 0, 50, 9, "Ovocuración restaura la mitad de los PS máximos del usuario."),
(94, "Pantalla de humo", 0, 0, 9, "Pantalla de Humo reduce la visión del rival. El rival pierde un turno."),
(95, "Perforador", 150, 0, 9, "Perforador provoca un daño severo al rival."),
(96, "Pisotón", 65, 0, 9, " Pisotea a los enemigos frente a sí para infligirles daño."),
(97, "Placaje", 40, 0, 9, "Choca con todas sus fuerzas contra los enemigos frente a sí para infligirles daño."),
(98, "Puño cometa", 90, 0, 9, "Realiza varios ataques infligiendo gran daño al oponente."),
(99, "Puño mareo", 70, 70, 9, "Causa daño y deja confundido al oponente, con lo cuál el rival pierde un turno."),
(100, "Recuperación", 0, 50, 9, "Recuperación permite recuperar el 50% total de puntos de vida."),
(101, "Reducción", 0, 0, 9, "Reducción permite ocultarse del oponente. El oponente pierde un turno."),
(102, "Remolino", 120, 120, 9, "Este ataque crea una enorme ráfaga de aire que daña al rival y lo hace perder un turno"),
(103, "Restricción", 20, 20, 9, "Inflige daño y quita un turno."),
(104, "Rizo defensa", 40, 30, 9, "Rueda a toda velocidad y erige un escudo a su alrededor. Mientras rueda, lanza por los aires a los rivales que alcanza."),
(105, "Rugido", 0, 0, 9, "El pokemon realiza un potente rugido que intimida a cualquier pokemon. Esto provoca que pierda un turno."),
(106, "Saña", 50, 50, 9, "Saña es una serie de ataques que inflige daño y confunde al oponente. El rival pierde una vida."),
(107, "Superdiente", 90, 0, 9, "Inflije daño a través de un potente mordisco."),
(108, "Supersónico", 40, 40, 9, "Es un ataque de sonido que confunde al rival. El opnente pierde un turno."),
(109, "Triataque", 80, 0, 9, "Imbuye su cuerpo de tres tipos de energía para atacar a los enemigos frente a sí. Puede quemar, paralizar o congelar."),
(110, "Venganza", 0, 0, 9, "Este movimiento provoca que el contrincante se paralice durante un turno."),
(111, "Viento cortante", 80, 0, 9, "Genera un poderoso remolino que lanza al contrincante para generale daño."),
(112, "Absorber", 40, 30, 10, "Realiza un ataque, inflige daño y recupera vida."),
(113, "Danza pétalo", 120, 0, 10, "Dispersa pétalos a su alrededor para dañar al oponente."),
(114, "Drenadoras", 90, 0, 10, "Dependiendo del pokemon, lanza semillas o enredaderas para infligir daño."),
(115, "Espora", 0, 0, 10, "Espora duerme al rival durante un turno"),
(116, "Hoja afilada", 55, 0, 10, "Lanza hojas cortantes que dañan al enemigo. Suele propinar un golpe crítico."),
(117, "Látigo cepa", 45, 0, 10, "Golpea hacia delante con lianas como látigos que infligen daño a los rivales en el área de efecto."),
(118, "Megaagotar", 60, 40, 10, "Ataca y absorve energpia."),
(119, "Paralizador", 0, 0, 10, "Paraliza al oponente."),
(120, "Rayo solar", 120, 0, 10, "Emite un intenso haz de luz que inflige daño a los rivales en el área de efecto."),
(121, "Somnífero", 0, 0, 10, "Somnífero duerme al objetivo."),
(122, "Agilidad", 40, 20, 11, "Agilidad permite al usuario moverse velozmente y provocar daño al rival. Además recupera una pequeña cantidad de vida."),
(123, "Amnesia", 0, 60, 11, "Hace olvidar el daño recibido. Aumenta los puntos de vida."),
(124, "Barrera", 0, 75, 11, "Barrera aumenta la cantidad de vida del usuario."),
(125, "Comesueños", 100, 100, 11, "Duerme al objetivo y ataca."),
(126, "Confusión", 50, 50, 11, "Causa daño y confunde al objetivo."),
(127, "Descanso", 0, 70, 11, "El usuario descansa y recupera vida"),
(128, "Hipnosis", 0, 0, 11, "Duerme al objetivo."),
(129, "Kinético", 30, 30, 11, "Realiza un ataque que inflige daño y deja confundido al rival"),
(130, "Meditación", 0, 30, 11, "Al usar meditación el usuario recupera vida."),
(131, "Psicoonda", 90, 0, 11, "Realiza un ataque a través de psicoondas."),
(132, "Psicorrayo", 65, 0, 11, "Realiza un ataque a través de psicoondas y además paraliza al usuario."),
(133, "Psíquico", 90, 30, 11, "Lanza un intenso y misterioso rayo de luz que daña a los enemigos a los que alcanza. Además recupera puntos de vida."),
(134, "Reflejo", 0, 50, 11, "Reflejo permite recuperar puntos de vida."),
(135, "Avalancha", 75, 0, 12, "Lanza una gran cantidad de rocas para infligir daño al oponente."),
(136, "Lanzarrocas", 50, 0, 13, "Lanza rocas al oponente para infligirle daño."),
(137, "Mordisco", 60, 0, 9, "Muerde al rival causándole daño."),
(138, "Ataque arena", 0, 0, 13, "Lanza arena al enemigo cegándolo durante un turno."),
(139, "Excavar", 80, 0, 13, "El usuario excava y lanza un ataque subterráneo."),
(140, "Fisura", 100, 0, 13, "Lanza un potente ataque que abre la tierra en la que se encuentra el oponente."),
(141, "Hueso palo", 65, 0, 13, "Realiza un ataque utilizando el hueso que posee."),
(142, "Huesomerang", 100, 0, 13, "Realiza un doble ataque con el hueso que posee."),
(143, "Terremoto", 150, 0, 13, " Salta muy alto y, tras aterrizar con violencia, inflige daño a los rivales en el área de efecto."),
(144, "Ácido", 40, 0, 14, "Lanza un chorro de ácido al oponente."),
(145, "Armadura ácida", 0, 30, 14, "Crea una armadura de ácido que le permite recuperar puntos de vida."),
(146, "Gas venenoso", 90, 90, 14, "Inflige daño y envenena al rival. El rival pierde un turno"),
(147, "Picotazo veneno", 25, 0, 14, "Lanza hacia delante agujas tóxicas que pueden envenenar a los enemigos alcanzados."),
(148, "Polución", 30, 0, 14, "Esparce veneno a su alrededor para causar daño a los enemigos."),
(149, "Polvo veneno", 0, 0, 14, "Este movimiento envenena al enemigo. Pierde un turno."),
(150, "Residuos", 65, 0, 14, "Lanza un ataque con materiales tóxicos."),
(151, "Tóxico", 60, 60, 14, "Ataca al enemigo y lo envenena. Pierde un turno."),
(152, "Ataque aéreo", 140, 0, 15, "Despliega las alas, se abalanza en la dirección seleccionada y, después, regresa a su ubicación original, infligiendo daño a los rivales en su trayectoria."),
(153, "Ataque ala", 60, 0, 15, "Golpea utilizando el ala."),
(154, "Pico taladro", 80, 0, 15, "Ataca a los enemigos que tiene delante con un afilado pico para infligirles daño."),
(155, "Picotazo", 35, 0, 15, "Ataca utilizando el pico."),
(156, "Tornado", 40, 0, 15, "Levanta un potente vendaval frente a sí que envuelve a los enemigos infligiéndoles daño."),
(157, "Vuelo", 90, 0, 15, "Emprende el vuelo y ataca al oponente de manera directa. El oponente pierde un turno.");

SELECT * FROM pokemon_game.attacks;